[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  metric_batch_size = 1000
  logfile = ""
  omit_hostname = false

[[inputs.http_response]]
  urls = ["http://app:8000/health"]
  method = "GET"
  response_timeout = "5s"
  name_override = "app_http_check"

  [inputs.http_response.tags]
    service = "monitoring-stack-demo"
    env = "${APP_ENV}"

[[outputs.influxdb_v2]]
  urls = ["${INFLUX_URL}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
